### ISSUE TITLE
Had to revert to fix 0 lidar packet issue

### ISSUE THREAD

**Issue by DevinBayly** [Krishtof-Korda/pcap-to-bag#11]
Hi there,

I've been a very content user of this tool, so thanks for all your work! I was returning to a project from back in December 2022, and the version of the code since aprils 348371e32a5f5d0d85696d04b1af11d4bdc86783 commit seems to cause an error where I see this when running the `pcap_to_bag` program

```
./devel/lib/pcap_to_bag/pcap_to_bag /place/Al-Rusafi-seq-2.pcap temp.bag 128
Written 0 lidar packets and 11577 imu packets
Duration: 115.781 seconds
```

However when I checkout that earlier commit I'm able to run the program with 
```
./devel/lib/pcap_to_bag/pcap_to_bag /place/Al-Rusafi-seq-2.pcap temp.bag 128
Written 148205 lidar packets and 11577 imu packets
Duration: 115.781 seconds
```

Not sure what's going on there. Thanks for any help! I'm also totally ok with using the older commit for now.

**Comment by Krishtof-Korda** [comment]
Hi Devin,

The latest commit changes the command line input from the number of laser
channels to the lidar payload size. This was done since we now have
multiple UDP packet profiles, each with unique payload sizes. Previously
the number of laser channels could be used to infer the LiDAR payload size.
However, now it must be input directly. You may reference the user manual
at static.ouster.dev/sensor-docs for a list of the LiDAR payload sizes and
the method to calculate it.

**Comment by DevinBayly** [comment]
Ok sounds good! Thanks for the heads up, I had lazily tried a few but didn't diligently cover that page before. I'll get on that right away =D
